import {
  findStartingSpace,
  getSpaceColumn,
  getSpaceSquare,
} from "../ts/retrivingFunctions";
import { solvePuzzle, Space } from "../ts/sodukuSolver";
import { expect, test } from "vitest";

test("Check column retriving is correct", () => {
  const space1: Space = { row: 0, column: 3 };
  const soduku1 = [
    [
      { changed: false, id: "A0", value: "4" },
      { changed: false, id: "B0", value: "1" },
      { changed: false, id: "C0", value: "" },
      { changed: false, id: "D0", value: "" },
      { changed: false, id: "E0", value: "6" },
      { changed: false, id: "F0", value: "" },
      { changed: false, id: "G0", value: "" },
      { changed: false, id: "H0", value: "7" },
      { changed: false, id: "I0", value: "" },
    ],
    [
      { changed: false, id: "A1", value: "" },
      { changed: false, id: "B1", value: "" },
      { changed: false, id: "C1", value: "3" },
      { changed: false, id: "D1", value: "" },
      { changed: false, id: "E1", value: "8" },
      { changed: false, id: "F1", value: "5" },
      { changed: false, id: "G1", value: "" },
      { changed: false, id: "H1", value: "" },
      { changed: false, id: "I1", value: "9" },
    ],
    [
      { changed: false, id: "A2", value: "" },
      { changed: false, id: "B2", value: "2" },
      { changed: false, id: "C2", value: "" },
      { changed: false, id: "D2", value: "3" },
      { changed: false, id: "E2", value: "7" },
      { changed: false, id: "F2", value: "" },
      { changed: false, id: "G2", value: "5" },
      { changed: false, id: "H2", value: "" },
      { changed: false, id: "I2", value: "1" },
    ],
    [
      { changed: false, id: "A3", value: "" },
      { changed: false, id: "B3", value: "3" },
      { changed: false, id: "C3", value: "" },
      { changed: false, id: "D3", value: "6" },
      { changed: false, id: "E3", value: "" },
      { changed: false, id: "F3", value: "9" },
      { changed: false, id: "G3", value: "2" },
      { changed: false, id: "H3", value: "5" },
      { changed: false, id: "I3", value: "" },
    ],
    [
      { changed: false, id: "A4", value: "6" },
      { changed: false, id: "B4", value: "" },
      { changed: false, id: "C4", value: "" },
      { changed: false, id: "D4", value: "5" },
      { changed: false, id: "E4", value: "" },
      { changed: false, id: "F4", value: "1" },
      { changed: false, id: "G4", value: "" },
      { changed: false, id: "H4", value: "" },
      { changed: false, id: "I4", value: "" },
    ],
    [
      { changed: false, id: "A5", value: "" },
      { changed: false, id: "B5", value: "" },
      { changed: false, id: "C5", value: "9" },
      { changed: false, id: "D5", value: "" },
      { changed: false, id: "E5", value: "2" },
      { changed: false, id: "F5", value: "" },
      { changed: false, id: "G5", value: "" },
      { changed: false, id: "H5", value: "" },
      { changed: false, id: "I5", value: "3" },
    ],
    [
      { changed: false, id: "A6", value: "" },
      { changed: false, id: "B6", value: "" },
      { changed: false, id: "C6", value: "6" },
      { changed: false, id: "D6", value: "2" },
      { changed: false, id: "E6", value: "" },
      { changed: false, id: "F6", value: "" },
      { changed: false, id: "G6", value: "7" },
      { changed: false, id: "H6", value: "4" },
      { changed: false, id: "I6", value: "5" },
    ],
    [
      { changed: false, id: "A7", value: "" },
      { changed: false, id: "B7", value: "" },
      { changed: false, id: "C7", value: "" },
      { changed: false, id: "D7", value: "4" },
      { changed: false, id: "E7", value: "" },
      { changed: false, id: "F7", value: "6" },
      { changed: false, id: "G7", value: "8" },
      { changed: false, id: "H7", value: "" },
      { changed: false, id: "I7", value: "" },
    ],
    [
      { changed: false, id: "A8", value: "2" },
      { changed: false, id: "B8", value: "8" },
      { changed: false, id: "C8", value: "4" },
      { changed: false, id: "D8", value: "" },
      { changed: false, id: "E8", value: "" },
      { changed: false, id: "F8", value: "" },
      { changed: false, id: "G8", value: "1" },
      { changed: false, id: "H8", value: "9" },
      { changed: false, id: "I8", value: "6" },
    ],
  ];
  expect(getSpaceColumn(space1, soduku1)).toEqual([
    "",
    "",
    "3",
    "6",
    "5",
    "",
    "2",
    "4",
    "",
  ]);
});

test("Check middle square retriving is correct", () => {
  const space1: Space = { row: 5, column: 3 };
  const soduku1 = [
    [
      { changed: false, id: "A0", value: "4" },
      { changed: false, id: "B0", value: "1" },
      { changed: false, id: "C0", value: "" },
      { changed: false, id: "D0", value: "" },
      { changed: false, id: "E0", value: "6" },
      { changed: false, id: "F0", value: "" },
      { changed: false, id: "G0", value: "" },
      { changed: false, id: "H0", value: "7" },
      { changed: false, id: "I0", value: "" },
    ],
    [
      { changed: false, id: "A1", value: "" },
      { changed: false, id: "B1", value: "" },
      { changed: false, id: "C1", value: "3" },
      { changed: false, id: "D1", value: "" },
      { changed: false, id: "E1", value: "8" },
      { changed: false, id: "F1", value: "5" },
      { changed: false, id: "G1", value: "" },
      { changed: false, id: "H1", value: "" },
      { changed: false, id: "I1", value: "9" },
    ],
    [
      { changed: false, id: "A2", value: "" },
      { changed: false, id: "B2", value: "2" },
      { changed: false, id: "C2", value: "" },
      { changed: false, id: "D2", value: "3" },
      { changed: false, id: "E2", value: "7" },
      { changed: false, id: "F2", value: "" },
      { changed: false, id: "G2", value: "5" },
      { changed: false, id: "H2", value: "" },
      { changed: false, id: "I2", value: "1" },
    ],
    [
      { changed: false, id: "A3", value: "" },
      { changed: false, id: "B3", value: "3" },
      { changed: false, id: "C3", value: "" },
      { changed: false, id: "D3", value: "6" },
      { changed: false, id: "E3", value: "" },
      { changed: false, id: "F3", value: "9" },
      { changed: false, id: "G3", value: "2" },
      { changed: false, id: "H3", value: "5" },
      { changed: false, id: "I3", value: "" },
    ],
    [
      { changed: false, id: "A4", value: "6" },
      { changed: false, id: "B4", value: "" },
      { changed: false, id: "C4", value: "" },
      { changed: false, id: "D4", value: "5" },
      { changed: false, id: "E4", value: "" },
      { changed: false, id: "F4", value: "1" },
      { changed: false, id: "G4", value: "" },
      { changed: false, id: "H4", value: "" },
      { changed: false, id: "I4", value: "" },
    ],
    [
      { changed: false, id: "A5", value: "" },
      { changed: false, id: "B5", value: "" },
      { changed: false, id: "C5", value: "9" },
      { changed: false, id: "D5", value: "" },
      { changed: false, id: "E5", value: "2" },
      { changed: false, id: "F5", value: "" },
      { changed: false, id: "G5", value: "" },
      { changed: false, id: "H5", value: "" },
      { changed: false, id: "I5", value: "3" },
    ],
    [
      { changed: false, id: "A6", value: "" },
      { changed: false, id: "B6", value: "" },
      { changed: false, id: "C6", value: "6" },
      { changed: false, id: "D6", value: "2" },
      { changed: false, id: "E6", value: "" },
      { changed: false, id: "F6", value: "" },
      { changed: false, id: "G6", value: "7" },
      { changed: false, id: "H6", value: "4" },
      { changed: false, id: "I6", value: "5" },
    ],
    [
      { changed: false, id: "A7", value: "" },
      { changed: false, id: "B7", value: "" },
      { changed: false, id: "C7", value: "" },
      { changed: false, id: "D7", value: "4" },
      { changed: false, id: "E7", value: "" },
      { changed: false, id: "F7", value: "6" },
      { changed: false, id: "G7", value: "8" },
      { changed: false, id: "H7", value: "" },
      { changed: false, id: "I7", value: "" },
    ],
    [
      { changed: false, id: "A8", value: "2" },
      { changed: false, id: "B8", value: "8" },
      { changed: false, id: "C8", value: "4" },
      { changed: false, id: "D8", value: "" },
      { changed: false, id: "E8", value: "" },
      { changed: false, id: "F8", value: "" },
      { changed: false, id: "G8", value: "1" },
      { changed: false, id: "H8", value: "9" },
      { changed: false, id: "I8", value: "6" },
    ],
  ];
  expect(getSpaceSquare(space1, soduku1)).toEqual([
    "6",
    "",
    "9",
    "5",
    "",
    "1",
    "",
    "2",
    "",
  ]);
});

test("Check top-right square retriving is correct", () => {
  const space1: Space = { row: 1, column: 1 };
  const soduku1 = [
    [
      { changed: false, id: "A0", value: "4" },
      { changed: false, id: "B0", value: "1" },
      { changed: false, id: "C0", value: "" },
      { changed: false, id: "D0", value: "" },
      { changed: false, id: "E0", value: "6" },
      { changed: false, id: "F0", value: "" },
      { changed: false, id: "G0", value: "" },
      { changed: false, id: "H0", value: "7" },
      { changed: false, id: "I0", value: "" },
    ],
    [
      { changed: false, id: "A1", value: "" },
      { changed: false, id: "B1", value: "" },
      { changed: false, id: "C1", value: "3" },
      { changed: false, id: "D1", value: "" },
      { changed: false, id: "E1", value: "8" },
      { changed: false, id: "F1", value: "5" },
      { changed: false, id: "G1", value: "" },
      { changed: false, id: "H1", value: "" },
      { changed: false, id: "I1", value: "9" },
    ],
    [
      { changed: false, id: "A2", value: "" },
      { changed: false, id: "B2", value: "2" },
      { changed: false, id: "C2", value: "" },
      { changed: false, id: "D2", value: "3" },
      { changed: false, id: "E2", value: "7" },
      { changed: false, id: "F2", value: "" },
      { changed: false, id: "G2", value: "5" },
      { changed: false, id: "H2", value: "" },
      { changed: false, id: "I2", value: "1" },
    ],
    [
      { changed: false, id: "A3", value: "" },
      { changed: false, id: "B3", value: "3" },
      { changed: false, id: "C3", value: "" },
      { changed: false, id: "D3", value: "6" },
      { changed: false, id: "E3", value: "" },
      { changed: false, id: "F3", value: "9" },
      { changed: false, id: "G3", value: "2" },
      { changed: false, id: "H3", value: "5" },
      { changed: false, id: "I3", value: "" },
    ],
    [
      { changed: false, id: "A4", value: "6" },
      { changed: false, id: "B4", value: "" },
      { changed: false, id: "C4", value: "" },
      { changed: false, id: "D4", value: "5" },
      { changed: false, id: "E4", value: "" },
      { changed: false, id: "F4", value: "1" },
      { changed: false, id: "G4", value: "" },
      { changed: false, id: "H4", value: "" },
      { changed: false, id: "I4", value: "" },
    ],
    [
      { changed: false, id: "A5", value: "" },
      { changed: false, id: "B5", value: "" },
      { changed: false, id: "C5", value: "9" },
      { changed: false, id: "D5", value: "" },
      { changed: false, id: "E5", value: "2" },
      { changed: false, id: "F5", value: "" },
      { changed: false, id: "G5", value: "" },
      { changed: false, id: "H5", value: "" },
      { changed: false, id: "I5", value: "3" },
    ],
    [
      { changed: false, id: "A6", value: "" },
      { changed: false, id: "B6", value: "" },
      { changed: false, id: "C6", value: "6" },
      { changed: false, id: "D6", value: "2" },
      { changed: false, id: "E6", value: "" },
      { changed: false, id: "F6", value: "" },
      { changed: false, id: "G6", value: "7" },
      { changed: false, id: "H6", value: "4" },
      { changed: false, id: "I6", value: "5" },
    ],
    [
      { changed: false, id: "A7", value: "" },
      { changed: false, id: "B7", value: "" },
      { changed: false, id: "C7", value: "" },
      { changed: false, id: "D7", value: "4" },
      { changed: false, id: "E7", value: "" },
      { changed: false, id: "F7", value: "6" },
      { changed: false, id: "G7", value: "8" },
      { changed: false, id: "H7", value: "" },
      { changed: false, id: "I7", value: "" },
    ],
    [
      { changed: false, id: "A8", value: "2" },
      { changed: false, id: "B8", value: "8" },
      { changed: false, id: "C8", value: "4" },
      { changed: false, id: "D8", value: "" },
      { changed: false, id: "E8", value: "" },
      { changed: false, id: "F8", value: "" },
      { changed: false, id: "G8", value: "1" },
      { changed: false, id: "H8", value: "9" },
      { changed: false, id: "I8", value: "6" },
    ],
  ];
  expect(getSpaceSquare(space1, soduku1)).toEqual([
    "4",
    "1",
    "",
    "",
    "",
    "3",
    "",
    "2",
    "",
  ]);
});
