import { solvePuzzle } from "../ts/sodukuSolver";
import { expect, test } from "vitest";

test("Check easy test is solved", () => {
  const soduku1 = [
    [
      { changed: true, id: "A0", value: "4" },
      { changed: true, id: "B0", value: "1" },
      { changed: false, id: "C0", value: "" },
      { changed: false, id: "D0", value: "" },
      { changed: true, id: "E0", value: "6" },
      { changed: false, id: "F0", value: "" },
      { changed: false, id: "G0", value: "" },
      { changed: true, id: "H0", value: "7" },
      { changed: false, id: "I0", value: "" },
    ],
    [
      { changed: false, id: "A1", value: "" },
      { changed: false, id: "B1", value: "" },
      { changed: true, id: "C1", value: "3" },
      { changed: false, id: "D1", value: "" },
      { changed: true, id: "E1", value: "8" },
      { changed: true, id: "F1", value: "5" },
      { changed: false, id: "G1", value: "" },
      { changed: false, id: "H1", value: "" },
      { changed: true, id: "I1", value: "9" },
    ],
    [
      { changed: false, id: "A2", value: "" },
      { changed: true, id: "B2", value: "2" },
      { changed: false, id: "C2", value: "" },
      { changed: true, id: "D2", value: "3" },
      { changed: true, id: "E2", value: "7" },
      { changed: false, id: "F2", value: "" },
      { changed: true, id: "G2", value: "5" },
      { changed: false, id: "H2", value: "" },
      { changed: true, id: "I2", value: "1" },
    ],
    [
      { changed: false, id: "A3", value: "" },
      { changed: true, id: "B3", value: "3" },
      { changed: false, id: "C3", value: "" },
      { changed: true, id: "D3", value: "6" },
      { changed: false, id: "E3", value: "" },
      { changed: true, id: "F3", value: "9" },
      { changed: true, id: "G3", value: "2" },
      { changed: true, id: "H3", value: "5" },
      { changed: false, id: "I3", value: "" },
    ],
    [
      { changed: true, id: "A4", value: "6" },
      { changed: false, id: "B4", value: "" },
      { changed: false, id: "C4", value: "" },
      { changed: true, id: "D4", value: "5" },
      { changed: false, id: "E4", value: "" },
      { changed: true, id: "F4", value: "1" },
      { changed: false, id: "G4", value: "" },
      { changed: false, id: "H4", value: "" },
      { changed: false, id: "I4", value: "" },
    ],
    [
      { changed: false, id: "A5", value: "" },
      { changed: false, id: "B5", value: "" },
      { changed: true, id: "C5", value: "9" },
      { changed: false, id: "D5", value: "" },
      { changed: true, id: "E5", value: "2" },
      { changed: false, id: "F5", value: "" },
      { changed: false, id: "G5", value: "" },
      { changed: false, id: "H5", value: "" },
      { changed: true, id: "I5", value: "3" },
    ],
    [
      { changed: false, id: "A6", value: "" },
      { changed: false, id: "B6", value: "" },
      { changed: true, id: "C6", value: "6" },
      { changed: true, id: "D6", value: "2" },
      { changed: false, id: "E6", value: "" },
      { changed: false, id: "F6", value: "" },
      { changed: true, id: "G6", value: "7" },
      { changed: true, id: "H6", value: "4" },
      { changed: true, id: "I6", value: "5" },
    ],
    [
      { changed: false, id: "A7", value: "" },
      { changed: false, id: "B7", value: "" },
      { changed: false, id: "C7", value: "" },
      { changed: true, id: "D7", value: "4" },
      { changed: false, id: "E7", value: "" },
      { changed: true, id: "F7", value: "6" },
      { changed: true, id: "G7", value: "8" },
      { changed: false, id: "H7", value: "" },
      { changed: false, id: "I7", value: "" },
    ],
    [
      { changed: true, id: "A8", value: "2" },
      { changed: true, id: "B8", value: "8" },
      { changed: true, id: "C8", value: "4" },
      { changed: false, id: "D8", value: "" },
      { changed: false, id: "E8", value: "" },
      { changed: false, id: "F8", value: "" },
      { changed: true, id: "G8", value: "1" },
      { changed: true, id: "H8", value: "9" },
      { changed: true, id: "I8", value: "6" },
    ],
  ];
  expect(solvePuzzle(soduku1).puzzle).toEqual([
    [
      { changed: true, id: "A0", value: "4" },
      { changed: true, id: "B0", value: "1" },
      { changed: true, id: "C0", value: "5" },
      { changed: true, id: "D0", value: "9" },
      { changed: true, id: "E0", value: "6" },
      { changed: true, id: "F0", value: "2" },
      { changed: true, id: "G0", value: "3" },
      { changed: true, id: "H0", value: "7" },
      { changed: true, id: "I0", value: "8" },
    ],
    [
      { changed: true, id: "A1", value: "7" },
      { changed: true, id: "B1", value: "6" },
      { changed: true, id: "C1", value: "3" },
      { changed: true, id: "D1", value: "1" },
      { changed: true, id: "E1", value: "8" },
      { changed: true, id: "F1", value: "5" },
      { changed: true, id: "G1", value: "4" },
      { changed: true, id: "H1", value: "2" },
      { changed: true, id: "I1", value: "9" },
    ],
    [
      { changed: true, id: "A2", value: "9" },
      { changed: true, id: "B2", value: "2" },
      { changed: true, id: "C2", value: "8" },
      { changed: true, id: "D2", value: "3" },
      { changed: true, id: "E2", value: "7" },
      { changed: true, id: "F2", value: "4" },
      { changed: true, id: "G2", value: "5" },
      { changed: true, id: "H2", value: "6" },
      { changed: true, id: "I2", value: "1" },
    ],
    [
      { changed: true, id: "A3", value: "8" },
      { changed: true, id: "B3", value: "3" },
      { changed: true, id: "C3", value: "1" },
      { changed: true, id: "D3", value: "6" },
      { changed: true, id: "E3", value: "4" },
      { changed: true, id: "F3", value: "9" },
      { changed: true, id: "G3", value: "2" },
      { changed: true, id: "H3", value: "5" },
      { changed: true, id: "I3", value: "7" },
    ],
    [
      { changed: true, id: "A4", value: "6" },
      { changed: true, id: "B4", value: "7" },
      { changed: true, id: "C4", value: "2" },
      { changed: true, id: "D4", value: "5" },
      { changed: true, id: "E4", value: "3" },
      { changed: true, id: "F4", value: "1" },
      { changed: true, id: "G4", value: "9" },
      { changed: true, id: "H4", value: "8" },
      { changed: true, id: "I4", value: "4" },
    ],
    [
      { changed: true, id: "A5", value: "5" },
      { changed: true, id: "B5", value: "4" },
      { changed: true, id: "C5", value: "9" },
      { changed: true, id: "D5", value: "8" },
      { changed: true, id: "E5", value: "2" },
      { changed: true, id: "F5", value: "7" },
      { changed: true, id: "G5", value: "6" },
      { changed: true, id: "H5", value: "1" },
      { changed: true, id: "I5", value: "3" },
    ],
    [
      { changed: true, id: "A6", value: "3" },
      { changed: true, id: "B6", value: "9" },
      { changed: true, id: "C6", value: "6" },
      { changed: true, id: "D6", value: "2" },
      { changed: true, id: "E6", value: "1" },
      { changed: true, id: "F6", value: "8" },
      { changed: true, id: "G6", value: "7" },
      { changed: true, id: "H6", value: "4" },
      { changed: true, id: "I6", value: "5" },
    ],
    [
      { changed: true, id: "A7", value: "1" },
      { changed: true, id: "B7", value: "5" },
      { changed: true, id: "C7", value: "7" },
      { changed: true, id: "D7", value: "4" },
      { changed: true, id: "E7", value: "9" },
      { changed: true, id: "F7", value: "6" },
      { changed: true, id: "G7", value: "8" },
      { changed: true, id: "H7", value: "3" },
      { changed: true, id: "I7", value: "2" },
    ],
    [
      { changed: true, id: "A8", value: "2" },
      { changed: true, id: "B8", value: "8" },
      { changed: true, id: "C8", value: "4" },
      { changed: true, id: "D8", value: "7" },
      { changed: true, id: "E8", value: "5" },
      { changed: true, id: "F8", value: "3" },
      { changed: true, id: "G8", value: "1" },
      { changed: true, id: "H8", value: "9" },
      { changed: true, id: "I8", value: "6" },
    ],
  ]);
});

// test("Check medium test is solved", () => {
//   const soduku1 = [
//     ["", "", "3", "9", "1", "6", "", "", "8"],
//     ["2", "", "", "4", "", "", "", "", "9"],
//     ["", "", "", "3", "", "", "", "7", ""],
//     ["", "", "", "", "9", "", "6", "2", ""],
//     ["", "4", "", "", "", "", "8", "1", ""],
//     ["", "", "", "", "6", "3", "", "9", "4"],
//     ["9", "", "", "", "", "", "", "", "1"],
//     ["1", "8", "5", "", "", "", "7", "", "6"],
//     ["", "7", "", "", "", "1", "", "8", "2"],
//   ];
//   expect(solvePuzzle(soduku1)).toEqual([
//     ["7", "5", "3", "9", "1", "6", "2", "4", "8"],
//     ["2", "1", "8", "4", "7", "5", "3", "6", "9"],
//     ["4", "9", "6", "3", "8", "2", "1", "7", "5"],
//     ["5", "3", "1", "8", "9", "4", "6", "2", "7"],
//     ["6", "4", "9", "5", "2", "7", "8", "1", "3"],
//     ["8", "2", "7", "1", "6", "3", "5", "9", "4"],
//     ["9", "6", "2", "7", "3", "8", "4", "5", "1"],
//     ["1", "8", "5", "2", "4", "9", "7", "3", "6"],
//     ["3", "7", "4", "6", "5", "1", "9", "8", "2"],
//   ]);
// });

// test("Check hard test is solved", () => {
//   const soduku1 = [
//     ["4", "", "", "9", "", "", "8", "6", ""],
//     ["", "", "", "", "", "7", "2", "", ""],
//     ["", "3", "", "2", "5", "", "", "", ""],
//     ["", "1", "7", "", "", "5", "", "2", "9"],
//     ["", "9", "", "", "2", "6", "", "", ""],
//     ["", "6", "", "", "9", "", "", "7", ""],
//     ["", "", "", "4", "", "", "5", "", ""],
//     ["7", "", "6", "", "", "", "9", "", ""],
//     ["", "", "", "", "6", "2", "4", "", ""],
//   ];
//   expect(solvePuzzle(soduku1)).toEqual([
//     ["4", "7", "2", "9", "1", "3", "8", "6", "5"],
//     ["9", "5", "1", "6", "8", "7", "2", "4", "3"],
//     ["6", "3", "8", "2", "5", "4", "7", "9", "1"],
//     ["8", "1", "7", "3", "4", "5", "6", "2", "9"],
//     ["3", "9", "4", "7", "2", "6", "1", "5", "8"],
//     ["2", "6", "5", "8", "9", "1", "3", "7", "4"],
//     ["1", "2", "3", "4", "7", "9", "5", "8", "6"],
//     ["7", "4", "6", "5", "3", "8", "9", "1", "2"],
//     ["5", "8", "9", "1", "6", "2", "4", "3", "7"],
//   ]);
// });
