export const puzzle = [
  ["4", "1", "x", "x", "6", "x", "x", "7", "x"],
  ["x", "x", "3", "x", "8", "5", "x", "x", "9"],
  ["x", "2", "x", "3", "7", "x", "5", "x", "1"],
  ["x", "3", "x", "6", "x", "9", "2", "5", "x"],
  ["6", "x", "x", "5", "x", "1", "x", "x", "x"],
  ["x", "x", "9", "x", "2", "x", "x", "x", "3"],
  ["x", "x", "6", "2", "x", "x", "7", "4", "5"],
  ["x", "x", "x", "4", "x", "6", "8", "x", "x"],
  ["2", "8", "4", "x", "x", "x", "1", "9", "6"],
];

export const newPuzzle = [
  [
    { changed: true, id: "A0", value: "4" },
    { changed: true, id: "B0", value: "1" },
    { changed: true, id: "C0", value: "5" },
    { changed: true, id: "D0", value: "9" },
    { changed: true, id: "E0", value: "6" },
    { changed: true, id: "F0", value: "2" },
    { changed: true, id: "G0", value: "3" },
    { changed: true, id: "H0", value: "7" },
    { changed: true, id: "I0", value: "8" },
  ],
  [
    { changed: true, id: "A1", value: "7" },
    { changed: true, id: "B1", value: "6" },
    { changed: true, id: "C1", value: "3" },
    { changed: true, id: "D1", value: "1" },
    { changed: true, id: "E1", value: "8" },
    { changed: true, id: "F1", value: "5" },
    { changed: true, id: "G1", value: "4" },
    { changed: true, id: "H1", value: "2" },
    { changed: true, id: "I1", value: "9" },
  ],
  [
    { changed: true, id: "A2", value: "9" },
    { changed: true, id: "B2", value: "2" },
    { changed: true, id: "C2", value: "8" },
    { changed: true, id: "D2", value: "3" },
    { changed: true, id: "E2", value: "7" },
    { changed: true, id: "F2", value: "4" },
    { changed: true, id: "G2", value: "5" },
    { changed: true, id: "H2", value: "6" },
    { changed: true, id: "I2", value: "1" },
  ],
  [
    { changed: true, id: "A3", value: "8" },
    { changed: true, id: "B3", value: "3" },
    { changed: true, id: "C3", value: "1" },
    { changed: true, id: "D3", value: "6" },
    { changed: true, id: "E3", value: "4" },
    { changed: true, id: "F3", value: "9" },
    { changed: true, id: "G3", value: "2" },
    { changed: true, id: "H3", value: "5" },
    { changed: true, id: "I3", value: "7" },
  ],
  [
    { changed: true, id: "A4", value: "6" },
    { changed: true, id: "B4", value: "7" },
    { changed: true, id: "C4", value: "2" },
    { changed: true, id: "D4", value: "5" },
    { changed: true, id: "E4", value: "3" },
    { changed: true, id: "F4", value: "1" },
    { changed: true, id: "G4", value: "9" },
    { changed: true, id: "H4", value: "8" },
    { changed: true, id: "I4", value: "4" },
  ],
  [
    { changed: true, id: "A5", value: "5" },
    { changed: true, id: "B5", value: "4" },
    { changed: true, id: "C5", value: "9" },
    { changed: true, id: "D5", value: "8" },
    { changed: true, id: "E5", value: "2" },
    { changed: true, id: "F5", value: "7" },
    { changed: true, id: "G5", value: "6" },
    { changed: true, id: "H5", value: "1" },
    { changed: true, id: "I5", value: "3" },
  ],
  [
    { changed: true, id: "A6", value: "3" },
    { changed: true, id: "B6", value: "9" },
    { changed: true, id: "C6", value: "6" },
    { changed: true, id: "D6", value: "2" },
    { changed: true, id: "E6", value: "1" },
    { changed: true, id: "F6", value: "8" },
    { changed: true, id: "G6", value: "7" },
    { changed: true, id: "H6", value: "4" },
    { changed: true, id: "I6", value: "5" },
  ],
  [
    { changed: true, id: "A7", value: "1" },
    { changed: true, id: "B7", value: "5" },
    { changed: true, id: "C7", value: "7" },
    { changed: true, id: "D7", value: "4" },
    { changed: true, id: "E7", value: "9" },
    { changed: true, id: "F7", value: "6" },
    { changed: true, id: "G7", value: "8" },
    { changed: true, id: "H7", value: "3" },
    { changed: true, id: "I7", value: "2" },
  ],
  [
    { changed: true, id: "A8", value: "2" },
    { changed: true, id: "B8", value: "8" },
    { changed: true, id: "C8", value: "4" },
    { changed: true, id: "D8", value: "7" },
    { changed: true, id: "E8", value: "5" },
    { changed: true, id: "F8", value: "3" },
    { changed: true, id: "G8", value: "1" },
    { changed: true, id: "H8", value: "9" },
    { changed: true, id: "I8", value: "6" },
  ],
];

const blankPuzzle = [
  [
    { changed: false, id: "A0", value: "" },
    { changed: false, id: "B0", value: "" },
    { changed: false, id: "C0", value: "" },
    { changed: false, id: "D0", value: "" },
    { changed: false, id: "E0", value: "" },
    { changed: false, id: "F0", value: "" },
    { changed: false, id: "G0", value: "" },
    { changed: false, id: "H0", value: "" },
    { changed: false, id: "I0", value: "" },
  ],
  [
    { changed: false, id: "A1", value: "" },
    { changed: false, id: "B1", value: "" },
    { changed: false, id: "C1", value: "" },
    { changed: false, id: "D1", value: "" },
    { changed: false, id: "E1", value: "" },
    { changed: false, id: "F1", value: "" },
    { changed: false, id: "G1", value: "" },
    { changed: false, id: "H1", value: "" },
    { changed: false, id: "I1", value: "" },
  ],
  [
    { changed: false, id: "A2", value: "" },
    { changed: false, id: "B2", value: "" },
    { changed: false, id: "C2", value: "" },
    { changed: false, id: "D2", value: "" },
    { changed: false, id: "E2", value: "" },
    { changed: false, id: "F2", value: "" },
    { changed: false, id: "G2", value: "" },
    { changed: false, id: "H2", value: "" },
    { changed: false, id: "I2", value: "" },
  ],
  [
    { changed: false, id: "A3", value: "" },
    { changed: false, id: "B3", value: "" },
    { changed: false, id: "C3", value: "" },
    { changed: false, id: "D3", value: "" },
    { changed: false, id: "E3", value: "" },
    { changed: false, id: "F3", value: "" },
    { changed: false, id: "G3", value: "" },
    { changed: false, id: "H3", value: "" },
    { changed: false, id: "I3", value: "" },
  ],
  [
    { changed: false, id: "A4", value: "" },
    { changed: false, id: "B4", value: "" },
    { changed: false, id: "C4", value: "" },
    { changed: false, id: "D4", value: "" },
    { changed: false, id: "E4", value: "" },
    { changed: false, id: "F4", value: "" },
    { changed: false, id: "G4", value: "" },
    { changed: false, id: "H4", value: "" },
    { changed: false, id: "I4", value: "" },
  ],
  [
    { changed: false, id: "A5", value: "" },
    { changed: false, id: "B5", value: "" },
    { changed: false, id: "C5", value: "" },
    { changed: false, id: "D5", value: "" },
    { changed: false, id: "E5", value: "" },
    { changed: false, id: "F5", value: "" },
    { changed: false, id: "G5", value: "" },
    { changed: false, id: "H5", value: "" },
    { changed: false, id: "I5", value: "" },
  ],
  [
    { changed: false, id: "A6", value: "" },
    { changed: false, id: "B6", value: "" },
    { changed: false, id: "C6", value: "" },
    { changed: false, id: "D6", value: "" },
    { changed: false, id: "E6", value: "" },
    { changed: false, id: "F6", value: "" },
    { changed: false, id: "G6", value: "" },
    { changed: false, id: "H6", value: "" },
    { changed: false, id: "I6", value: "" },
  ],
  [
    { changed: false, id: "A7", value: "" },
    { changed: false, id: "B7", value: "" },
    { changed: false, id: "C7", value: "" },
    { changed: false, id: "D7", value: "" },
    { changed: false, id: "E7", value: "" },
    { changed: false, id: "F7", value: "" },
    { changed: false, id: "G7", value: "" },
    { changed: false, id: "H7", value: "" },
    { changed: false, id: "I7", value: "" },
  ],
  [
    { changed: false, id: "A8", value: "" },
    { changed: false, id: "B8", value: "" },
    { changed: false, id: "C8", value: "" },
    { changed: false, id: "D8", value: "" },
    { changed: false, id: "E8", value: "" },
    { changed: false, id: "F8", value: "" },
    { changed: false, id: "G8", value: "" },
    { changed: false, id: "H8", value: "" },
    { changed: false, id: "I8", value: "" },
  ],
];

export const puzzle2 = [
  ["x", "x", "3", "9", "1", "6", "x", "x", "8"],
  ["2", "x", "x", "4", "x", "x", "x", "x", "9"],
  ["x", "x", "x", "3", "x", "x", "x", "7", "x"],
  ["x", "x", "x", "x", "9", "x", "6", "2", "x"],
  ["x", "4", "x", "x", "x", "x", "8", "1", "x"],
  ["x", "x", "x", "x", "6", "3", "x", "9", "4"],
  ["9", "x", "x", "x", "x", "x", "x", "x", "1"],
  ["1", "8", "5", "x", "x", "x", "7", "x", "6"],
  ["x", "7", "x", "x", "x", "1", "x", "8", "2"],
];

export const puzzle3 = [
  ["4", "x", "x", "9", "x", "x", "8", "6", "x"],
  ["x", "x", "x", "x", "x", "7", "2", "x", "x"],
  ["x", "3", "x", "2", "5", "x", "x", "x", "x"],
  ["x", "1", "7", "x", "x", "5", "x", "2", "9"],
  ["x", "9", "x", "x", "2", "6", "x", "x", "x"],
  ["x", "6", "x", "x", "9", "x", "x", "7", "x"],
  ["x", "x", "x", "4", "x", "x", "5", "x", "x"],
  ["7", "x", "6", "x", "x", "x", "9", "x", "x"],
  ["x", "x", "x", "x", "6", "2", "4", "x", "x"],
];

export const puzzle4 = [
  ["4", "x", "x", "x", "x", "x", "8", "3", "x"],
  ["x", "x", "x", "x", "x", "x", "x", "4", "x"],
  ["x", "x", "x", "8", "2", "x", "x", "x", "x"],
  ["x", "6", "x", "x", "x", "x", "x", "x", "x"],
  ["x", "8", "x", "x", "7", "x", "x", "x", "x"],
  ["x", "x", "x", "2", "9", "x", "5", "x", "1"],
  ["5", "x", "1", "x", "x", "x", "9", "x", "4"],
  ["x", "x", "9", "3", "x", "x", "x", "x", "7"],
  ["x", "x", "x", "x", "5", "9", "x", "x", "3"],
];
